### ISSUE TITLE
I don't know what's the situation

### ISSUE THREAD

**Issue by 649432699** [KAKETAKAGE/PixivAlbum#1]
![微信截图_20210720182500](https://user-images.githubusercontent.com/50725122/126309844-32a8d0ef-15a6-4528-85e3-b9c30adb69ac.png)
 nan+59F

**Comment by KATAGARA** [comment]
这个应该是没有 `安装目录\collect\pixiv_collect.exe` 文件造成的
尝试安装 `PixivAlbum-Setup-0.0.1-xxx-with-PixivCollect.exe` , 或者在 [PixivCollect/releases](https://github.com/KAKETAKAGE/PixivCollect/releases)  中下载 `pixiv_collect.exe` 并放入 `collect` 文件夹中来解决

**Comment by 649432699** [comment]
![微信图片_20210720221932](https://user-images.githubusercontent.com/50725122/126340281-3f792db7-1c4f-4748-8d38-962219f9d289.png)
我拉进去了，不过打开是这样的

**Comment by KATAGARA** [comment]
1. 只需要在这个文件放在这里就可以了, 你看下 [如何使用](https://github.com/KAKETAKAGE/PixivAlbum#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8), 在软件中操作.
2.  `MongoDB` 没有配置好, 或者服务没有启动

**Comment by 649432699** [comment]
我是跟着流程走的，然后打开一直都是白屏+呼叫小姐姐中，我看视频collect中也是两个文件，我删了其他的也不行，还是上面那个报错。MongoDB我也是跟着教程走的，打开是这样的
![微信截图_20210721000936](https://user-images.githubusercontent.com/50725122/126358601-1be5f5c9-de7b-44c7-904e-19837dc42488.png)
![微信截图_20210721000746](https://user-images.githubusercontent.com/50725122/126358637-9afb48e4-6fe6-4b58-b4f8-2afd51590929.png)
下的是这个PixivAlbum-Setup-0.0.1-x64-with-PixivCollect.exe。

**Comment by KATAGARA** [comment]
1. 图2直接点 `connect` 你看下能不能访问成功
2. 成功的话, 你尝试下以管理员运行软件
3. 还是不行的话, 可能是未知的bug

**Comment by 649432699** [comment]
![微信截图_20210721173222](https://user-images.githubusercontent.com/50725122/126466860-6edbd6fe-8e9b-4e84-9007-d2fe8bcae70f.png)
打不开，转了很久

**Comment by KATAGARA** [comment]
那你就是 MongoDB没有安装好.
你进入 `任务管理器->服务->MongoDB `
看下有没有 `MongoDB`, 没有表示你没有安装 `MongoDB`, 有的话把服务启动状态会变为 `正在运行`

**Comment by KATAGARA** [comment]
或者按 `win+r` 键, 输入`services.msc` , 进入服务界面

**Comment by 649432699** [comment]
![微信截图_20210721212642](https://user-images.githubusercontent.com/50725122/126496358-6005c99b-2f1b-478e-9516-b97ce82d421a.png)
启动不了，这是系统问题？

**Comment by KATAGARA** [comment]
系统问题, 可能是没有管理员权限造成的. 尝试把现在的登录账户设置成管理员

**Comment by 649432699** [comment]
用过管理员登录运行，还是不行

**Comment by KATAGARA** [comment]
不是管理员运行软件, 是你账户可能没有管理员权限来启动服务. 这个是系统问题, 不是软件问题, 我也不能明确指出解决方法

**Comment by 649432699** [comment]
系统问题就算了，先不整了。感谢大佬的耐心解答。辛苦了
